site_name: Do micro ao macro - Introdução à termoestatística
nav:
  - Home Page: index.md
  - Ciclos Termodinâmicos:
    - Ciclo de Carnot: ciclos/Carnot/carnot.md
    - Ciclo Diesel: ciclos/Diesel/diesel.md
    - Ciclo Stirling: ciclos/Stirling/stirling.md
    - Ciclo Joule: ciclos/Joule/joule.md
    - Ciclo Otto: ciclos/Otto/Otto.md
  - O Caixeiro Viajante: caixeiro.md
  - Os Autores: autores.md
  - Blog: 
    - blog/index.md
  - Sobre este Produto: produto_educacional.md
theme:
  name: material
  custom_dir: overrides
  font:
    text: Noto Sans
    code: Cascadia Code'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt-br
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: white
      accent: green 
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: black
      accent: deep orange
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/valdeirfilho

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
plugins:
  - blog



copyright: |
  &copy; 2023 <a href="https://github.com/doMicroAoMacro"  target="_blank" rel="noopener">Valdeir Filho</a>

  